# Generated by Django 4.2.1 on 2023-05-30 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_fin', models.DateTimeField(auto_created=True)),
                ('fecha_inicio', models.DateTimeField(auto_created=True)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaFin', models.DateField(auto_created=True)),
                ('fechaInicio', models.DateField(auto_created=True)),
                ('salario', models.CharField(max_length=7)),
                ('cargo', models.CharField(max_length=35)),
                ('descripcionCargo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(default='0', max_length=12)),
                ('correo', models.CharField(max_length=100)),
                ('numCelular', models.CharField(max_length=20)),
                ('numTelefono', models.CharField(max_length=12)),
                ('ciudad', models.CharField(max_length=15)),
                ('direccion', models.TextField(default=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], max_length=30)),
                ('idContrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst_api.contratos')),
            ],
        ),
        migrations.CreateModel(
            name='PrestacionSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripion', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='TipoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CEDULA', 'Induccion'), ('REINDUCCION', 'Reinduccion'), ('ENTRENAMIENTO', 'Entrenamiento'), ('CAPACITACION', 'Capacitacion')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CEDULA', 'Fijo'), ('PARCIAL', 'Parcial')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CEDULA', 'Cedula'), ('LIBRETA_MILITAR', 'Libreta militar'), ('HOJA_DE_VIDA', 'Hoja de vida'), ('CERTIFICADOS_EDUCACION', 'Certificados de estudio'), ('CARTAS_EXPERIENCIA_LABORAL', 'Cartas de experiencia laboral'), ('CERTIFICADO_EPS', 'Certificado EPS'), ('CERTIFICADO_PENSION', 'Certificado Pensión'), ('BENEFICIOS', 'Beneficios'), ('OTROS', 'Otros')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NOMINA', 'Nomina'), ('PRESTACIONES_SOCIALES', 'Prestaciones_sociales'), ('CONTRATO', 'Contrato')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Retiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_created=True)),
                ('descripcion', models.TextField()),
                ('entregaDeImplementos', models.BooleanField()),
                ('idContrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst_api.contratos')),
            ],
        ),
        migrations.CreateModel(
            name='PrestacionesPorContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idContrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst_api.contratos')),
                ('idPrestacionSocial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst_api.prestacionsocial')),
            ],
        ),
        migrations.CreateModel(
            name='Liquidaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(auto_created=True)),
                ('fecha_pago', models.DateField(auto_created=True)),
                ('fecha_fin', models.DateField(auto_created=True)),
                ('fecha_inicio', models.DateField(auto_created=True)),
                ('valor', models.CharField(default='0', max_length=7)),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst_api.empleados')),
                ('tipoLiquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst_api.tipoliquidacion')),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_created=True)),
                ('descripcion', models.TextField()),
                ('observaciones', models.TextField()),
                ('idRetiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst_api.retiros')),
            ],
        ),
        migrations.CreateModel(
            name='EmpleadosEnActividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultadoEvaluativo', models.CharField(choices=[('APROBADO', 'Aprobado'), ('DESAPROBADO', 'Desaprobado')], max_length=12)),
                ('observaciones', models.TextField()),
                ('idActividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst_api.actividades')),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst_api.empleados')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentosEmpleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='employees')),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst_api.empleados')),
                ('idTipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst_api.tipodocumento')),
            ],
        ),
        migrations.AddField(
            model_name='contratos',
            name='tipoContrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst_api.tipocontrato'),
        ),
        migrations.AddField(
            model_name='actividades',
            name='tipoActividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyst_api.tipoactividad'),
        ),
    ]
