# Generated by Django 4.2.1 on 2023-06-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst_api', '0003_remove_empleados_idcontrato_contratos_idempleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocontrato',
            name='tipo',
            field=models.CharField(choices=[('FIJO', 'Fijo'), ('PARCIAL', 'Parcial')], max_length=30),
        ),
    ]
