# Generated by Django 4.2.1 on 2023-06-04 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyst_api', '0004_alter_tipocontrato_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos',
            name='fechaFin',
        ),
    ]
