# Generated by Django 4.2.1 on 2023-06-04 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyst_api', '0005_remove_contratos_fechafin'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='idContrato',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='analyst_api.documentosempleados'),
        ),
    ]
