# Generated by Django 4.2.1 on 2023-06-06 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst_api', '0006_contratos_idcontrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='salario',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tipoactividad',
            name='tipo',
            field=models.CharField(choices=[('INDUCCION', 'Induccion'), ('REINDUCCION', 'Reinduccion'), ('ENTRENAMIENTO', 'Entrenamiento'), ('CAPACITACION', 'Capacitacion')], max_length=30),
        ),
    ]
