# Generated by Django 4.2.1 on 2023-06-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst_api', '0007_alter_contratos_salario_alter_tipoactividad_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadosenactividades',
            name='resultadoEvaluativo',
            field=models.CharField(blank=True, choices=[('APROBADO', 'Aprobado'), ('DESAPROBADO', 'Desaprobado')], max_length=12),
        ),
    ]
