# Generated by Django 4.2.1 on 2023-07-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst_api', '0008_alter_empleadosenactividades_resultadoevaluativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='direccion',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='numTelefono',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='resultadosEntrevista',
            field=models.TextField(),
        ),
    ]
