# Generated by Django 4.2.1 on 2023-07-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst_api', '0009_alter_empleados_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividades',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='actividades',
            name='fecha_inicio',
            field=models.DateField(),
        ),
    ]
