# Generated by Django 4.2.1 on 2023-07-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst_api', '0010_alter_actividades_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadosenactividades',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
    ]
