# Generated by Django 4.2.1 on 2023-05-14 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aplicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Aplicantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cedula', models.CharField(default='0', max_length=12)),
                ('correo', models.CharField(max_length=100)),
                ('contrasena', models.CharField(max_length=50)),
                ('numCelular', models.CharField(max_length=20)),
                ('numTelefono', models.CharField(max_length=12)),
                ('ciudad', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
                ('escolaridad', models.CharField(choices=[('PRIMARIA', 'Primaria'), ('BACHILLER', 'Bachiller'), ('TECNICO', 'Técnico'), ('PROFESIONAL', 'Profesional')], default='BACHILLER', max_length=12)),
                ('manejoIngles', models.BooleanField(default=False)),
                ('speaking', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], max_length=5)),
                ('writing', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], max_length=5)),
                ('listening', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], max_length=5)),
                ('experienciaLaboral', models.CharField(max_length=2)),
                ('dispuestoTraslado', models.BooleanField(default=False)),
                ('trabajarHorasExtra', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estadoDisponibilidad', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=7)),
                ('vacantes', models.CharField(max_length=3)),
                ('fechaInicio', models.DateField()),
                ('salario', models.CharField(max_length=7)),
                ('experienciaAnos', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CEDULA', 'Cedula'), ('LIBRETA_MILITAR', 'Libreta militar'), ('HOJA_DE_VIDA', 'Hoja de vida'), ('CERTIFICADOS_EDUCACION', 'Certificados de estudio'), ('CARTAS_EXPERIENCIA_LABORAL', 'Cartas de experiencia laboral'), ('CERTIFICADO_EPS', 'Certificado EPS'), ('CERTIFICADO_PENSION', 'Certificado Pensión'), ('BENEFICIOS', 'Beneficios'), ('OTROS', 'Otros')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Seleccionados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faseAplicante', models.CharField(choices=[('PRESELECCION', 'Preselección'), ('SELECCION', 'Selección'), ('CONTRATACION', 'Contratación')], max_length=13)),
                ('idAplicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicant_employee_api.aplicaciones')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentosAplicantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('archivo', models.FileField(upload_to='../media')),
                ('idAplicante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicant_employee_api.aplicantes')),
                ('idTipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicant_employee_api.tipodocumento')),
            ],
        ),
        migrations.AddField(
            model_name='aplicaciones',
            name='idAplicante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicant_employee_api.aplicantes'),
        ),
        migrations.AddField(
            model_name='aplicaciones',
            name='idOferta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicant_employee_api.ofertas'),
        ),
    ]
