# Generated by Django 4.2.1 on 2023-05-15 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicant_employee_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentosaplicantes',
            name='nombre',
        ),
    ]
