# Generated by Django 4.2.1 on 2023-05-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicant_employee_api', '0002_remove_documentosaplicantes_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicantes',
            name='certificaciones',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='aplicantes',
            name='titulo',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='aplicantes',
            name='direccion',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='aplicantes',
            name='dispuestoTraslado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='aplicantes',
            name='manejoIngles',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='aplicantes',
            name='trabajarHorasExtra',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='documentosaplicantes',
            name='archivo',
            field=models.FileField(upload_to='media/'),
        ),
    ]
