# Generated by Django 4.2.1 on 2023-05-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicant_employee_api', '0003_aplicantes_certificaciones_aplicantes_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicantes',
            name='contratado',
            field=models.BooleanField(default=False),
        ),
    ]
