# Generated by Django 4.2.1 on 2023-05-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicant_employee_api', '0004_aplicantes_contratado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosaplicantes',
            name='archivo',
            field=models.FileField(upload_to='aplicants'),
        ),
    ]
