# Generated by Django 4.2.1 on 2023-05-31 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicant_employee_api', '0005_alter_documentosaplicantes_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertas',
            name='salario',
            field=models.CharField(max_length=10),
        ),
    ]
