# Generated by Django 4.2.1 on 2023-06-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicant_employee_api', '0006_alter_ofertas_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seleccionados',
            name='faseAplicante',
            field=models.CharField(choices=[('SELECCION', 'Selección'), ('PRE_CONTRATACION', 'Precontratación')], max_length=17),
        ),
    ]
