# Generated by Django 4.2.1 on 2023-07-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicant_employee_api', '0009_alter_aplicantes_certificaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicantes',
            name='certificaciones',
            field=models.TextField(blank=True),
        ),
    ]
