# Generated by Django 4.2.1 on 2023-07-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicant_employee_api', '0010_alter_aplicantes_certificaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicantes',
            name='escolaridad',
            field=models.CharField(choices=[('NINGUNA', 'Ninguna'), ('PRIMARIA', 'Primaria'), ('BACHILLER', 'Bachiller'), ('TECNICO', 'Técnico'), ('PROFESIONAL', 'Profesional')], default='BACHILLER', max_length=12),
        ),
        migrations.AlterField(
            model_name='aplicantes',
            name='listening',
            field=models.CharField(choices=[('NINGUNA', 'Ninguna'), ('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], max_length=7),
        ),
        migrations.AlterField(
            model_name='aplicantes',
            name='speaking',
            field=models.CharField(choices=[('NINGUNA', 'Ninguna'), ('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], max_length=7),
        ),
        migrations.AlterField(
            model_name='aplicantes',
            name='writing',
            field=models.CharField(choices=[('NINGUNA', 'Ninguna'), ('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], max_length=7),
        ),
    ]
