# Generated by Django 4.2.1 on 2023-07-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicant_employee_api', '0011_alter_aplicantes_escolaridad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicantes',
            name='certificaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='aplicantes',
            name='dispuestoTraslado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aplicantes',
            name='numTelefono',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='aplicantes',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='aplicantes',
            name='trabajarHorasExtra',
            field=models.BooleanField(default=False),
        ),
    ]
